<#	
	.NOTES
	===========================================================================
	 Created on:   	2022-11-30 10:44 PM
	 Created by:   	Marc Collins
	 Filename:     	BuildModule.ps1
	 Version:     	1.0.2022.1130
	===========================================================================
	.DESCRIPTION
		This uses a Environment variable `GH_TOKEN` to connect to GitHub to pull information about the Reporitory, 
		The Module Manifest informaiton will be automatically generated by this script.
		All setting can be hardcoded in the Module_Config.json if necessary.
		Files placed in the SRC subfolder will be compiled into the Module
#>

[CmdletBinding()]
param
(
	[system.IO.DirectoryInfo]$BuildRoot = $(Get-Item $PWD),
	[switch]$ExportAll
)

$DirSeparator = $([system.io.path]::DirectorySeparatorChar)
$BinDIR = 'bin'
[system.IO.FileInfo]$ConfigFile = "$($BuildRoot.FullName)$($DirSeparator)Module_Config.json"
if ($ConfigFile.Exists) {
	$Config = Get-Content "$($BuildRoot.FullName)$($DirSeparator)Module_Config.json" | ConvertFrom-Json
} else {
	$Config = [ordered]@{ RepositoryURI = 'https://localhost'; ModuleName = "$($BuildRoot.Name)"; ModuleManifest = @{ Author = $null; CompanyName = $null; Copyright = $null; Description = $null; DotNetFrameworkVersion = $null; FileList = $null; FunctionsToExport = $null; Guid = $null; HelpInfoUri = $null; LicenseUri = $null; ModuleVersion = $null; PrivateData = $null; ProjectUri = $null; ReleaseNotes = $null; Tags = $null; } }
	ConvertTo-Json $Config | Out-File -Encoding utf8 -FilePath $ConfigFile.FullName
}

$paramNewModuleManifest = @{
	Guid = [guid]::NewGuid()
}

if ($Null -eq $Env:GH_TOKEN) {
	$RequiredValues = $true
	Write-Warning "This build is primariy designed to run as a GitHub Action: Ensure `$Env:GH_Token is set"
	if ($null -eq $Config.RepositoryURI) {
		Write-Warning 'You must specify the RepositoryURI in the Config.json'
		$RequiredValues = $false
	} else {
		$RepositoryURI = $Config.RepositoryURI
	}
	
	if ($null -eq $Config.ModuleName) {
		Write-Warning 'You must specify the ModuleName in the Config.json'
		$RequiredValues = $false
	} else {
		$ModuleName = $Config.ModuleName
	}
	
	if ($RequiredValues -eq $false) {
		return
	}
} else {
	$GH_TOKEN = $Env:GH_TOKEN
	$RepositoryURI = "$($Env:GITHUB_API_URL)/repos/$($Env:GITHUB_REPOSITORY)"
	$RepositoryInfo = Invoke-RestMethod $RepositoryURI -ContentType 'application/json' -Headers @{
		Authorization = "Bearer $GH_TOKEN"
	}
	$RepositoryOwnerInfo = Invoke-RestMethod $RepositoryInfo.owner.url -ContentType 'application/json' -Headers @{
		Authorization = "Bearer $GH_TOKEN"
	}
	
	$Author = $RepositoryOwnerInfo.name
	if ($Null -ne $RepositoryOwnerInfo.company) {
		$Company = $RepositoryOwnerInfo.company
	} else {
		$Company = $RepositoryOwnerInfo.login
	}
	$ModuleName = $RepositoryInfo.name
}

if ($Null -ne $Config.ModuleManifest.Author) {
	$paramNewModuleManifest.Author = $Config.ModuleManifest.Author
} elseif ($Null -ne $RepositoryInfo) {
	$paramNewModuleManifest.Author = $Author
}

if ($Null -ne $Config.ModuleManifest.CompanyName) {
	$paramNewModuleManifest.CompanyName = $Config.ModuleManifest.CompanyName
} elseif ($Null -ne $RepositoryInfo) {
	$paramNewModuleManifest.CompanyName = $Company
}

if ($Null -ne $Config.ModuleManifest.Copyright) {
	$paramNewModuleManifest.Copyright = $Config.ModuleManifest.Copyright
}

if ($Null -ne $Config.ModuleManifest.Description) {
	$paramNewModuleManifest.Description = $Config.ModuleManifest.Description
} elseif ($Null -ne $RepositoryInfo) {
	$paramNewModuleManifest.Description = $RepositoryInfo.Description
}

if ($Null -ne $Config.ModuleManifest.DotNetFrameworkVersion) {
	$paramNewModuleManifest.DotNetFrameworkVersion = $Config.ModuleManifest.DotNetFrameworkVersion
}

if ($Null -ne $Config.ModuleManifest.FileList) {
	$paramNewModuleManifest.FileList = $Config.ModuleManifest.FileList
}

if ($Null -ne $Config.ModuleManifest.Guid) {
	$paramNewModuleManifest.Guid = $Config.ModuleManifest.Guid
} elseif ($Null -ne $Env:GITHUB_SHA) {
	$paramNewModuleManifest.Guid = [guid]::Parse($Env:GITHUB_SHA.Substring(0, 32))
}

if ($Null -ne $Config.ModuleManifest.HelpInfoUri) {
	$paramNewModuleManifest.HelpInfoUri = $Config.ModuleManifest.HelpInfoUri
} elseif ($Null -ne $RepositoryInfo) {
	if ($Null -ne $RepositoryInfo.homepage) {
		$paramNewModuleManifest.HelpInfoUri = $RepositoryInfo.homepage
	} elseif ($RepositoryInfo.has_issues) {
		$paramNewModuleManifest.HelpInfoUri = "$($RepositoryInfo.html_url)/issues"
	} else {
		$paramNewModuleManifest.HelpInfoUri = $RepositoryInfo.html_url
	}
}

if ($Null -ne $Config.ModuleManifest.LicenseUri) {
	$paramNewModuleManifest.LicenseUri = $Config.ModuleManifest.LicenseUri
} elseif ($Null -ne $RepositoryInfo) {
	$paramNewModuleManifest.LicenseUri = "$($RepositoryInfo.html_url)/blob/$($env:GITHUB_REF_NAME)/LICENSE"
}

if ($Null -ne $Config.ModuleManifest.PrivateData) {
	$paramNewModuleManifest.PrivateData = $Config.ModuleManifest.PrivateData
}

if ($Null -ne $Config.ModuleManifest.ProjectUri) {
	$paramNewModuleManifest.ProjectUri = $Config.ModuleManifest.ProjectUri
} elseif ($Null -ne $RepositoryInfo) {
	$paramNewModuleManifest.ProjectUri = $RepositoryInfo.html_url
}

if ($Null -ne $Config.ModuleManifest.Tags) {
	$paramNewModuleManifest.Tags = $Config.ModuleManifest.Tags
} elseif ($Null -ne $RepositoryInfo) {
	# $paramNewModuleManifest.Tags = $RepositoryInfo.Tags ### CheckTHIS
}

#####################################################################

#Set the Version
if ($Null -ne $Config.ModuleManifest.ModuleVersion) {
	$Version = [version]::new($Config.ModuleManifest.ModuleVersion)
} else {
	try {
		$Tag = $(git tag -l --sort=refname v* | Select-Object -Last 1)
	} catch {
	}
	if ($Null -eq $Tag) {
		$Tag = 'v0.0.0.0'
	}
	try {
		$Version = [version]::new(($Tag).substring(1));
	} catch {
		$Version = [version]::new('0.0.0.0');
	}
}
$ModuleVersion = [version]::new("$($Version.Major).$($Version.Minor).$("$([datetime]::utcnow.ToString('yy'))$([datetime]::UtcNow.DayOfYear.ToString('000'))").$([datetime]::UtcNow.TimeOfDay.TotalSeconds.ToString('#'))")

if ($Null -ne $Config.ModuleManifest.ReleaseNotes) {
	$paramNewModuleManifest.ReleaseNotes = $Config.ModuleManifest.ReleaseNotes
} elseif ($Null -ne $RepositoryInfo) {
	$paramNewModuleManifest.ReleaseNotes = "$($RepositoryInfo.html_url)/releases/tag/v$($ModuleVersion)"
}

$paramNewModuleManifest.ModuleVersion = $ModuleVersion
$RootModule = "$($ModuleName).psm1"
$ModuleManifest = "$($ModuleName).psd1"
$paramNewModuleManifest.path = $ModuleManifest
$paramNewModuleManifest.RootModule = $RootModule
$SRCDir = Join-Path $BuildRoot src
$ScriptFiles = Get-ChildItem $SRCDir -Recurse -Include '*.ps1' | Where-Object { 
	-not ($_.FullName -match '\\bin\\' -or $_.FullName -match '\\Resources\\' -or $_.Name -like 'Build-*') 
} | Sort-Object -Property DirectoryName,BaseName

$paramNewModuleManifest.FileList = $ScriptFiles| ForEach-Object {
join-path $_.Directory.name $_.Name
}

$ModuleDIR = $Null

[System.io.DirectoryInfo]$ModuleDir = Join-Path -Path $BuildRoot -ChildPath $ModuleName |Join-Path -ChildPath $ModuleVersion
$ModuleDIR.Refresh()
if ($ModuleDIR.Exists) {
	Write-Host "Clearing Existing DIR: $($ModuleDIR.FullName)"
	try {
		$ModuleDir.Delete($true)
	} catch {
		Write-Error 'Module DIR exists and files are locked'
		return $Null
	}
	
	Start-Sleep -Seconds 1
	$ModuleDIR.Refresh()
}
$ModuleDir.Create()
$ModuleDIR.Refresh()
$ModuleZip = [System.IO.FileInfo]::new("$($BuildRoot.FullName)$($DirSeparator)$($ModuleName).zip").FullName

$ScriptContent = foreach ($ScriptFile in $ScriptFiles) {
	Get-Content $ScriptFile.FullName
}

if ($Null -ne $Config.AllowDynamicContent -and $Config.AllowDynamicContent -eq $true) {
	$moduleContent = . (Join-Path -Path $SRCDir -ChildPath "Resources/BuildFiles/Scripts/DynamicLoading.ps1")
	Get-ChildItem $SRCDir -Directory -Exclude Resources | Where-Object { $_.GetFiles().Count -gt 0 } | Copy-Item -Destination $ModuleDIR -Recurse -Force
} else {
	$moduleContent = $ScriptContent 
}

[system.io.fileInfo]$RMMD = Join-Path $SRCDir -ChildPath 'ReadMe.md'
if (-not $RMMD.Exists){
	[system.io.fileInfo]$RRMMD = Join-Path $BuildRoot -ChildPath 'ReadMe.md'
	if($RRMMD.Exists){
		Copy-Item $RRMMD.FullName -Destination $(Join-Path $ModuleDIR -ChildPath 'ReadMe.md') -Force
	}
}
$MDs = Get-ChildItem $SRCDir -Filter '*.md'
foreach ($MD in $MDs) {
	if ($MD.Exists) {
		Copy-Item -Path $MD.FullName -Destination "$($ModuleDIR.FullName)$($DirSeparator)"
	}
}

$BinPath = Join-Path -Path $BuildRoot -ChildPath 'src' |Join-Path -ChildPath $BinDIR
if (-not [string]::IsNullOrEmpty($BinPath)) {
	$Directories = Get-ChildItem $BinPath -Recurse -Directory
	$Modules = $Directories | Where-Object {
		$_.GetFiles('*.psd1').Count -gt 0
	}
	$Assemblies = $Directories | Where-Object {
		$_.GetFiles('*.psd1').Count -eq 0
	}
	
	if ($Modules.count -gt 0) {
		$NestedModules = $Modules.GetFiles('*.psd1').FullName.substring($BinPath.length - $BinDIR.length)
		$Modules | ForEach-Object {
			#"$($ModuleDir.FullName)$($_.FullName.Substring($BinPath.length - $BinDIR.length - 1))"
			Copy-Item -Recurse -Path $_.FullName -Destination "$($ModuleDir.FullName)$($_.FullName.Substring($BinPath.length - $BinDIR.length - 1))"
		}
		$paramNewModuleManifest.NestedModules = $NestedModules
		$paramNewModuleManifest.ModuleList = $NestedModules
	}
	
	if ($Assemblies.count -gt 0) {
		$RequiredDLLs = $Assemblies.GetFiles('*.dll').FullName.substring($BinPath.length - $BinDIR.length)
		$Assemblies.GetFiles('*.dll') | ForEach-Object {
			[system.io.fileInfo]$destfile = "$($ModuleDir.FullName)$($_.FullName.Substring($BinPath.length - $BinDIR.length - 1))"
			$null = $destfile.Directory.Create()
			Copy-Item -Recurse -Path $_.FullName -Destination "$($ModuleDir.FullName)$($_.FullName.Substring($BinPath.length - $BinDIR.length - 1))"
		}
		$paramNewModuleManifest.RequiredAssemblies = $RequiredDLLs
	}
}

Push-Location $ModuleDir.FullName
$moduleContent| Out-File $RootModule -Encoding utf8

if ($Null -ne $Config.ModuleManifest.FunctionsToExport) {
	$paramNewModuleManifest.FunctionsToExport = $Config.ModuleManifest.FunctionsToExport
} else {
	[regex]$FunctionName = [regex]::new('(?<=function )([\w]+-[\w]+)(?>[\s]+\{)', [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
	if ($ExportAll) {
		[regex]$FunctionName = [regex]::new('(?<=[\s]?function )([\w]+-?[\w]+)(?>[\s]+\{)', [System.Text.RegularExpressions.RegexOptions]::IgnoreCase)
	}
	$paramNewModuleManifest.FunctionsToExport = $FunctionName.Matches($ScriptContent).ForEach({ $_.Groups[1].value }) | Sort-Object -Unique
}

if ($Null -ne $Config.ModuleManifest.CmdletsToExport) {
	$paramNewModuleManifest.CmdletsToExport = $Config.ModuleManifest.CmdletsToExport
} else {
	$paramNewModuleManifest.CmdletsToExport = @()
}

if ($Null -ne $Config.ModuleManifest.VariablesToExport) {
	$paramNewModuleManifest.VariablesToExport = $Config.ModuleManifest.VariablesToExport
} else {
	$paramNewModuleManifest.VariablesToExport = @()
}

if ($Null -ne $Config.ModuleManifest.AliasesToExport) {
	$paramNewModuleManifest.AliasesToExport = $Config.ModuleManifest.AliasesToExport
} else {
	$paramNewModuleManifest.AliasesToExport = @()
}

#Write-Warning $($paramNewModuleManifest | ConvertTo-Json)
New-ModuleManifest @paramNewModuleManifest
Pop-Location
Compress-Archive -Path $ModuleDir -DestinationPath $ModuleZip -CompressionLevel Optimal -Force

"Version=v$($ModuleVersion)" >> $ENV:GITHUB_OUTPUT
"ModuleName=$($ModuleName)" >> $ENV:GITHUB_OUTPUT
"ModuleDir=$($ModuleDir.FullName)" >> $ENV:GITHUB_OUTPUT
"ModuleDirRelative=$(Resolve-Path -Relative $ModuleDir.FullName)" >> $ENV:GITHUB_OUTPUT
"ModuleZip=$($ModuleZip)" >> $ENV:GITHUB_OUTPUT

'### Finished! :rocket:' >> $env:GITHUB_STEP_SUMMARY
"#### Built ``$($ModuleName)``" >> $env:GITHUB_STEP_SUMMARY
"#### Version ``$($ModuleVersion)``" >> $env:GITHUB_STEP_SUMMARY
if ($($paramNewModuleManifest.FunctionsToExport | Measure-Object).count -gt 0) {
	'##### Functions Included' >> $env:GITHUB_STEP_SUMMARY
	($paramNewModuleManifest.FunctionsToExport | ForEach-Object {
		"- ``$($_)``"
	}) >> $env:GITHUB_STEP_SUMMARY
}

if ($($paramNewModuleManifest.VariablesToExport | Measure-Object).count -gt 0) {
	'##### Variables Included' >> $env:GITHUB_STEP_SUMMARY
	($paramNewModuleManifest.VariablesToExport | ForEach-Object {
		"- ``$($_)``"
	}) >> $env:GITHUB_STEP_SUMMARY
}

if ($($paramNewModuleManifest.CmdletsToExport | Measure-Object).count -gt 0) {
	'##### Cmdlets Included' >> $env:GITHUB_STEP_SUMMARY
	($paramNewModuleManifest.CmdletsToExport | ForEach-Object {
		"- ``$($_)``"
	}) >> $env:GITHUB_STEP_SUMMARY
}
if ($($paramNewModuleManifest.AliasesToExport | Measure-Object).count -gt 0) {
	'##### Aliases Included' >> $env:GITHUB_STEP_SUMMARY
	($paramNewModuleManifest.AliasesToExport | ForEach-Object {
		"- ``$($_)``"
	}) >> $env:GITHUB_STEP_SUMMARY
}
